# File: pubspec.yaml

name: runepriest
description: A top-down RPG with sandbox elements and story-driven narrative.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.6
  lints: ^6.0.0
